server:
  port: 8089

logging:
  path: logs
  level:
    com:
      example:
        notify: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.229.84:3306/playground
    username: root
    password: 1qaz2wsx3

app:
  firebase-adminsdk-key-file: ./pg-iap-test-21265333-firebase-adminsdk-azey0-f361217b3d.json